version: 2

executorType: docker

containerInfo:
  - image: node:7.5.0
    env:
      - NODE_ENV=prod

stages:

  build:
    workDir: ~/pano

    steps:
      - type: checkout

      - restore_cache:
          keys:
            - node_modules

      - run:
          name: Installing dependencies
          command: npm install

      - save_cache:
          key: node_modules
          paths:
            - ~/pano/node_modules

      - run:
          name: Running tests
          command: npm test

      # - run:
          # name: Uploading coverage report
          # command: npm install -g codeclimate-test-reporter && codeclimate-test-reporter < coverage/lcov.info
